name: Composite Action
# description: Dummy action that only prints ${{ github.ref }}
description: Dummy action that only prints 

runs:
  using: "composite"
  steps:
#     - uses: korea-dinos/ajaykn-public-1/.github/actions/composite@main
#     - uses: korea-dinos/ajaykn-public/test-action1@main
    - uses: actions/checkout@v3
    - uses: ./test-action1
#     - uses: korea-dinos/ajaykn-public@main
    - name: Print messages
      shell: bash
      run: |
        set -x
        echo "dummy message v16.0.0 tag"
