name: Composite Action - test1
# description: Dummy action that only prints ${{ github.ref }}
description: Dummy action that only prints 

runs:
  using: "composite"
  steps:
    - name: Print messages
      shell: bash
      run: |
        set -x
        echo "dummy message test 1 tag"
