# This is a basic workflow to help you get started with Actions

name: Call-Action-Submodule

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call-action-directly:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: korea-dinos/ajaykn-public-action@main
      
  call-another-action:
    runs-on: ubuntu-latest
    steps:
      - uses: korea-dinos/ajaykn-submodule/test-action@main
    
  call-action-via-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: korea-dinos/ajaykn-submodule/vendor-actions/ajaykn-public-action@main

  call-action-via-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: korea-dinos/ajaykn-submodule
          submodules: true
      - run: |
          pwd && ls -R
      - uses: ./vendor-actions/ajaykn-public-action
