name: Caller JSONize
on: workflow_dispatch

jobs:
  welcome_party:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "welcome to world of callable workflows"

  call_the_workflow:
    uses: korea-dinos/ajaykn-public/.github/workflows/callable1.yml@main
  
  goodbye_party:
    runs-on: ubuntu-latest
    needs: call_the_workflow
    steps:
    - run: echo "and we're done!"
